# AlertHawk Metrics – least-privilege ClusterRole and ClusterRoleBinding
# Apply: kubectl apply -f alerthawk-metrics-rbac.yaml
# Prerequisites: namespace alerthawk and service account alerthawk-sa must exist

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alerthawk-metrics-collector
rules:
  # Core API – events (namespaced)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "get"]
  # Core API – nodes (cluster-scoped)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  # Core API – node proxy (PVC/stats summary)
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  # Core API – pods (namespaced)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  # Core API – pod logs (when COLLECT_LOGS=true)
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  # Metrics API – node and pod metrics
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["list", "get"]
  # Version endpoint (for GetVersionAsync / cloud detection)
  - nonResourceURLs: ["/version"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alerthawk-metrics-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alerthawk-metrics-collector
subjects:
  - kind: ServiceAccount
    name: alerthawk-sa
    namespace: alerthawk
